### ISSUE TITLE
rowHeight should be configurable

### ISSUE THREAD

**Issue by bmathews** [conorhastings/react-syntax-highlighter-virtualized-renderer#1]
Depending on the font size or line height, the rowHeight prop passed to the virtualized list will need to be configurable.

**Comment by conorhastings** [comment]
ahh yeah, that makes sense, definitely oversight on my part, should be easy enough, just default to 15 and allow overriding. 

Thinking of allowing explciit height and with as well, and defaulting to AutoSizer, what do you think?

**Comment by bmathews** [comment]
That could be convenient, but I can't think of a scenario where a consumer couldn't just wrap what you currently have in some other container though.

**Comment by conorhastings** [comment]
@bmathews yeah that's a good point, didn't think about that

**Comment by conorhastings** [comment]
@bmathews published as `v1.1.0`
